-- Schema simplificado para Checkpoint
SET NOCOUNT ON;

IF OBJECT_ID('dbo.Movimiento', 'U') IS NOT NULL
 DROP TABLE dbo.Movimiento;
IF OBJECT_ID('dbo.Stock', 'U') IS NOT NULL
 DROP TABLE dbo.Stock;
IF OBJECT_ID('dbo.Ubicacion', 'U') IS NOT NULL
 DROP TABLE dbo.Ubicacion;
IF OBJECT_ID('dbo.Sede', 'U') IS NOT NULL
 DROP TABLE dbo.Sede;
IF OBJECT_ID('dbo.Lote', 'U') IS NOT NULL
 DROP TABLE dbo.Lote;
IF OBJECT_ID('dbo.Producto', 'U') IS NOT NULL
 DROP TABLE dbo.Producto;
IF OBJECT_ID('dbo.[UserRole]', 'U') IS NOT NULL
 DROP TABLE dbo.[UserRole];
IF OBJECT_ID('dbo.Rol', 'U') IS NOT NULL
 DROP TABLE dbo.Rol;
IF OBJECT_ID('dbo.[Usuario]', 'U') IS NOT NULL
 DROP TABLE dbo.[Usuario];
IF OBJECT_ID('dbo.CalidadLiberacion', 'U') IS NOT NULL
 DROP TABLE dbo.CalidadLiberacion;

CREATE TABLE Producto(
 Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
 Sku NVARCHAR(50) NOT NULL UNIQUE,
 Nombre NVARCHAR(120) NOT NULL,
 Unidad NVARCHAR(10) NOT NULL,
 VidaUtilDias INT NOT NULL,
 TempMin DECIMAL(5,2) NULL,
 TempMax DECIMAL(5,2) NULL,
 StockMinimo DECIMAL(18,3) NOT NULL,
 Activo BIT NOT NULL DEFAULT 1
);

CREATE TABLE Lote(
 Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
 ProductoId UNIQUEIDENTIFIER NOT NULL REFERENCES Producto(Id),
 CodigoLote NVARCHAR(60) NOT NULL,
 FechaIngreso DATETIME NOT NULL,
 FechaVencimiento DATETIME NULL,
 OrdenCompra NVARCHAR(60) NULL,
 GuiaRecepcion NVARCHAR(60) NULL,
 TempIngreso DECIMAL(5,2) NULL,
 Estado NVARCHAR(15) NOT NULL CHECK (Estado IN ('Pendiente','Liberado','Bloqueado'))
);

CREATE TABLE Sede(
 Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
 Nombre NVARCHAR(100) NOT NULL,
 Codigo NVARCHAR(30) NOT NULL UNIQUE,
 Direccion NVARCHAR(200) NULL,
 Activa BIT NOT NULL DEFAULT 1
);

CREATE TABLE Ubicacion(
 Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
 SedeId UNIQUEIDENTIFIER NOT NULL REFERENCES Sede(Id),
 Codigo NVARCHAR(50) NOT NULL,
 Tipo NVARCHAR(30) NULL,
 Capacidad DECIMAL(18,3) NULL,
 CONSTRAINT UQ_Ubicacion_Sede_Codigo UNIQUE (SedeId, Codigo)
);

CREATE TABLE Stock(
 Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
 LoteId UNIQUEIDENTIFIER NOT NULL REFERENCES Lote(Id),
 UbicacionId UNIQUEIDENTIFIER NOT NULL REFERENCES Ubicacion(Id),
 Cantidad DECIMAL(18,3) NOT NULL CHECK (Cantidad >=0),
 Unidad NVARCHAR(10) NOT NULL,
 ActualizadoEn DATETIME NOT NULL DEFAULT(GETDATE()),
 CONSTRAINT UQ_Stock_Lote_Ubicacion UNIQUE (LoteId, UbicacionId)
);

CREATE TABLE Movimiento(
 Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
 LoteId UNIQUEIDENTIFIER NOT NULL REFERENCES Lote(Id),
 SedeId UNIQUEIDENTIFIER NOT NULL REFERENCES Sede(Id),
 OrigenUbicacionId UNIQUEIDENTIFIER NULL REFERENCES Ubicacion(Id),
 DestinoUbicacionId UNIQUEIDENTIFIER NULL REFERENCES Ubicacion(Id),
 Tipo NVARCHAR(15) NOT NULL CHECK (Tipo IN ('Ingreso','Movimiento','Salida','Devolucion','Ajuste')),
 Cantidad DECIMAL(18,3) NOT NULL,
 Unidad NVARCHAR(10) NOT NULL,
 Fecha DATETIME NOT NULL DEFAULT(GETDATE()),
 UsuarioId UNIQUEIDENTIFIER NULL,
 Motivo NVARCHAR(200) NULL
);

CREATE TABLE [Usuario](
 Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
 Nombre NVARCHAR(120) NOT NULL,
 Email NVARCHAR(120) NOT NULL UNIQUE,
 PasswordHash NVARCHAR(256) NOT NULL,
 Activo BIT NOT NULL DEFAULT 1
);

CREATE TABLE Rol(
 Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
 Nombre NVARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE [UserRole](
 UsuarioId UNIQUEIDENTIFIER NOT NULL REFERENCES [Usuario](Id),
 RolId UNIQUEIDENTIFIER NOT NULL REFERENCES Rol(Id),
 AsignadoEn DATETIME NOT NULL DEFAULT(GETDATE()),
 AsignadoPorUsuarioId UNIQUEIDENTIFIER NULL,
 CONSTRAINT PK_UserRole PRIMARY KEY (UsuarioId, RolId)
);

CREATE TABLE CalidadLiberacion(
 Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
 LoteId UNIQUEIDENTIFIER NOT NULL REFERENCES Lote(Id),
 UsuarioId UNIQUEIDENTIFIER NOT NULL REFERENCES [Usuario](Id),
 Fecha DATETIME NOT NULL DEFAULT(GETDATE()),
 Estado NVARCHAR(15) NOT NULL,
 Observacion NVARCHAR(300) NULL,
 EvidenciaUrl NVARCHAR(300) NULL
);

-- Índices adicionales
CREATE INDEX IX_Producto_Sku ON Producto(Sku);
CREATE INDEX IX_Lote_ProductoId ON Lote(ProductoId);
CREATE INDEX IX_Ubicacion_SedeId ON Ubicacion(SedeId);
CREATE INDEX IX_Stock_UbicacionId ON Stock(UbicacionId);
CREATE INDEX IX_Movimiento_LoteId ON Movimiento(LoteId);
